//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `rgblight.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public class InvalidColorRangeException extends com.zeroc.Ice.UserException
{
    public InvalidColorRangeException()
    {
        this.message = "Value out of bounds";
    }

    public InvalidColorRangeException(Throwable cause)
    {
        super(cause);
        this.message = "Value out of bounds";
    }

    public InvalidColorRangeException(short badValue, short minValue, short maxValue, String message)
    {
        this.badValue = badValue;
        this.minValue = minValue;
        this.maxValue = maxValue;
        this.message = message;
    }

    public InvalidColorRangeException(short badValue, short minValue, short maxValue, String message, Throwable cause)
    {
        super(cause);
        this.badValue = badValue;
        this.minValue = minValue;
        this.maxValue = maxValue;
        this.message = message;
    }

    public String ice_id()
    {
        return "::SmartHome::InvalidColorRangeException";
    }

    public short badValue;

    public short minValue;

    public short maxValue;

    public String message;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::SmartHome::InvalidColorRangeException", -1, true);
        ostr_.writeShort(badValue);
        ostr_.writeShort(minValue);
        ostr_.writeShort(maxValue);
        ostr_.writeString(message);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        badValue = istr_.readShort();
        minValue = istr_.readShort();
        maxValue = istr_.readShort();
        message = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = -1441020128L;
}
