//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `preset.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public class NonExistentPreset extends com.zeroc.Ice.UserException
{
    public NonExistentPreset()
    {
        this.badName = "";
        this.message = "Preset with a given name does not exist";
    }

    public NonExistentPreset(Throwable cause)
    {
        super(cause);
        this.badName = "";
        this.message = "Preset with a given name does not exist";
    }

    public NonExistentPreset(String badName, String message)
    {
        this.badName = badName;
        this.message = message;
    }

    public NonExistentPreset(String badName, String message, Throwable cause)
    {
        super(cause);
        this.badName = badName;
        this.message = message;
    }

    public String ice_id()
    {
        return "::SmartHome::NonExistentPreset";
    }

    public String badName;

    public String message;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::SmartHome::NonExistentPreset", -1, true);
        ostr_.writeString(badName);
        ostr_.writeString(message);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        badName = istr_.readString();
        message = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = 616425776L;
}
