//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `rgblight.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public class RgbLightRequest implements java.lang.Cloneable,
                                        java.io.Serializable
{
    public RgbLightOperation operation;

    public Color color;

    public String presetName;

    public RgbLightRequest()
    {
        this.operation = RgbLightOperation.CLASSIC;
        this.color = new Color();
        this.presetName = "";
    }

    public RgbLightRequest(RgbLightOperation operation, Color color, String presetName)
    {
        this.operation = operation;
        this.color = color;
        this.presetName = presetName;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        RgbLightRequest r = null;
        if(rhs instanceof RgbLightRequest)
        {
            r = (RgbLightRequest)rhs;
        }

        if(r != null)
        {
            if(this.operation != r.operation)
            {
                if(this.operation == null || r.operation == null || !this.operation.equals(r.operation))
                {
                    return false;
                }
            }
            if(this.color != r.color)
            {
                if(this.color == null || r.color == null || !this.color.equals(r.color))
                {
                    return false;
                }
            }
            if(this.presetName != r.presetName)
            {
                if(this.presetName == null || r.presetName == null || !this.presetName.equals(r.presetName))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::SmartHome::RgbLightRequest");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, operation);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, color);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, presetName);
        return h_;
    }

    public RgbLightRequest clone()
    {
        RgbLightRequest c = null;
        try
        {
            c = (RgbLightRequest)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        RgbLightOperation.ice_write(ostr, this.operation);
        Color.ice_write(ostr, this.color);
        ostr.writeString(this.presetName);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.operation = RgbLightOperation.ice_read(istr);
        this.color = Color.ice_read(istr);
        this.presetName = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, RgbLightRequest v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public RgbLightRequest ice_read(com.zeroc.Ice.InputStream istr)
    {
        RgbLightRequest v = new RgbLightRequest();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<RgbLightRequest> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, RgbLightRequest v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<RgbLightRequest> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(RgbLightRequest.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final RgbLightRequest _nullMarshalValue = new RgbLightRequest();

    /** @hidden */
    public static final long serialVersionUID = 96668776L;
}
