//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `thermostat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public interface ThermostatPrx extends com.zeroc.Ice.ObjectPrx
{
    default float getTemperature()
    {
        return getTemperature(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default float getTemperature(java.util.Map<String, String> context)
    {
        return _iceI_getTemperatureAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Float> getTemperatureAsync()
    {
        return _iceI_getTemperatureAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Float> getTemperatureAsync(java.util.Map<String, String> context)
    {
        return _iceI_getTemperatureAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Float> _iceI_getTemperatureAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Float> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getTemperature", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     float ret;
                     ret = istr.readFloat();
                     return ret;
                 });
        return f;
    }

    default float setTemperature(ThermostatRequest request)
        throws InvalidTemperatureRangeException,
               NonExistentPreset
    {
        return setTemperature(request, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default float setTemperature(ThermostatRequest request, java.util.Map<String, String> context)
        throws InvalidTemperatureRangeException,
               NonExistentPreset
    {
        try
        {
            return _iceI_setTemperatureAsync(request, context, true).waitForResponseOrUserEx();
        }
        catch(InvalidTemperatureRangeException ex)
        {
            throw ex;
        }
        catch(NonExistentPreset ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.Float> setTemperatureAsync(ThermostatRequest request)
    {
        return _iceI_setTemperatureAsync(request, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Float> setTemperatureAsync(ThermostatRequest request, java.util.Map<String, String> context)
    {
        return _iceI_setTemperatureAsync(request, context, false);
    }

    /**
     * @hidden
     * @param iceP_request -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Float> _iceI_setTemperatureAsync(ThermostatRequest iceP_request, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Float> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "setTemperature", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_setTemperature);
        f.invoke(true, context, null, ostr -> {
                     ThermostatRequest.ice_write(ostr, iceP_request);
                 }, istr -> {
                     float ret;
                     ret = istr.readFloat();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_setTemperature =
    {
        InvalidTemperatureRangeException.class,
        NonExistentPreset.class
    };

    default java.util.Map<java.lang.String, java.lang.Float> getPresets()
    {
        return getPresets(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default java.util.Map<java.lang.String, java.lang.Float> getPresets(java.util.Map<String, String> context)
    {
        return _iceI_getPresetsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.util.Map<java.lang.String, java.lang.Float>> getPresetsAsync()
    {
        return _iceI_getPresetsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.util.Map<java.lang.String, java.lang.Float>> getPresetsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getPresetsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.util.Map<java.lang.String, java.lang.Float>> _iceI_getPresetsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.util.Map<java.lang.String, java.lang.Float>> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getPresets", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     java.util.Map<java.lang.String, java.lang.Float> ret;
                     ret = TemperaturePresetsHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default void addPreset(String name, float temperature)
        throws InvalidTemperatureRangeException
    {
        addPreset(name, temperature, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void addPreset(String name, float temperature, java.util.Map<String, String> context)
        throws InvalidTemperatureRangeException
    {
        try
        {
            _iceI_addPresetAsync(name, temperature, context, true).waitForResponseOrUserEx();
        }
        catch(InvalidTemperatureRangeException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> addPresetAsync(String name, float temperature)
    {
        return _iceI_addPresetAsync(name, temperature, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> addPresetAsync(String name, float temperature, java.util.Map<String, String> context)
    {
        return _iceI_addPresetAsync(name, temperature, context, false);
    }

    /**
     * @hidden
     * @param iceP_name -
     * @param iceP_temperature -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_addPresetAsync(String iceP_name, float iceP_temperature, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "addPreset", null, sync, _iceE_addPreset);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_name);
                     ostr.writeFloat(iceP_temperature);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_addPreset =
    {
        InvalidTemperatureRangeException.class
    };

    default void editPreset(String name, float temperature)
        throws InvalidTemperatureRangeException
    {
        editPreset(name, temperature, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void editPreset(String name, float temperature, java.util.Map<String, String> context)
        throws InvalidTemperatureRangeException
    {
        try
        {
            _iceI_editPresetAsync(name, temperature, context, true).waitForResponseOrUserEx();
        }
        catch(InvalidTemperatureRangeException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> editPresetAsync(String name, float temperature)
    {
        return _iceI_editPresetAsync(name, temperature, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> editPresetAsync(String name, float temperature, java.util.Map<String, String> context)
    {
        return _iceI_editPresetAsync(name, temperature, context, false);
    }

    /**
     * @hidden
     * @param iceP_name -
     * @param iceP_temperature -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_editPresetAsync(String iceP_name, float iceP_temperature, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "editPreset", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_editPreset);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_name);
                     ostr.writeFloat(iceP_temperature);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_editPreset =
    {
        InvalidTemperatureRangeException.class
    };

    default void removePreset(String name)
    {
        removePreset(name, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void removePreset(String name, java.util.Map<String, String> context)
    {
        _iceI_removePresetAsync(name, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> removePresetAsync(String name)
    {
        return _iceI_removePresetAsync(name, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> removePresetAsync(String name, java.util.Map<String, String> context)
    {
        return _iceI_removePresetAsync(name, context, false);
    }

    /**
     * @hidden
     * @param iceP_name -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_removePresetAsync(String iceP_name, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "removePreset", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_name);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ThermostatPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ThermostatPrx.class, _ThermostatPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ThermostatPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ThermostatPrx.class, _ThermostatPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ThermostatPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ThermostatPrx.class, _ThermostatPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ThermostatPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ThermostatPrx.class, _ThermostatPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ThermostatPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ThermostatPrx.class, _ThermostatPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ThermostatPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ThermostatPrx.class, _ThermostatPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ThermostatPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ThermostatPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ThermostatPrx ice_adapterId(String newAdapterId)
    {
        return (ThermostatPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ThermostatPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ThermostatPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ThermostatPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ThermostatPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ThermostatPrx ice_invocationTimeout(int newTimeout)
    {
        return (ThermostatPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ThermostatPrx ice_connectionCached(boolean newCache)
    {
        return (ThermostatPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ThermostatPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ThermostatPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ThermostatPrx ice_secure(boolean b)
    {
        return (ThermostatPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ThermostatPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ThermostatPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ThermostatPrx ice_preferSecure(boolean b)
    {
        return (ThermostatPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ThermostatPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ThermostatPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ThermostatPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ThermostatPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ThermostatPrx ice_collocationOptimized(boolean b)
    {
        return (ThermostatPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ThermostatPrx ice_twoway()
    {
        return (ThermostatPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ThermostatPrx ice_oneway()
    {
        return (ThermostatPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ThermostatPrx ice_batchOneway()
    {
        return (ThermostatPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ThermostatPrx ice_datagram()
    {
        return (ThermostatPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ThermostatPrx ice_batchDatagram()
    {
        return (ThermostatPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ThermostatPrx ice_compress(boolean co)
    {
        return (ThermostatPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ThermostatPrx ice_timeout(int t)
    {
        return (ThermostatPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ThermostatPrx ice_connectionId(String connectionId)
    {
        return (ThermostatPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ThermostatPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ThermostatPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::SmartHome::Thermostat";
    }
}
